ecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from django.views.generic import TemplateView
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/auth/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/auth/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('', include('store.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

from rest_framework import routers

from store.views import ProductDetailView, ProductListView, CategoryViewSet, ProductDetail,\
     ProductList, CategoryDetail, CategoryList, CountryList, CountryDetail, CityList, CityDetail


router = routers.DefaultRouter()

urlpatterns = [
    path('api/', include(router.urls)),
    path('api/products/', ProductList.as_view()),
    path('api/products/<pk>/', ProductDetail.as_view()),
    path('api/category/', CategoryList.as_view()),

    path('api/category/', CategoryList.as_view()),
    path('api/category/<pk>/', CategoryDetail.as_view()),

    path('api/country/', CountryList.as_view()),
    path('api/country/<pk>/', CountryDetail.as_view()),

    path('api/city/', CityList.as_view()),
    path('api/city/<pk>/', CityDetail.as_view()),


    path('login', TemplateView.as_view(template_name="login.html"), name='login'),
    path('list', ProductListView.as_view(), name='list'),
    path('detail/<pk>', ProductDetailView.as_view(), name='detail'),
    path('', TemplateView.as_view(template_name="base.html"), name='home'),

]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

import uuid

# Create your models here.

class UserProfile(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    mobile_phone = models.fields.CharField(max_length=50)
    upload = models.FileField(upload_to='uploads/')


class Country(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.fields.CharField(max_length=100)

    def __str__(self):
        return self.name


class City(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    country = models.ForeignKey(
        Country,
        related_name='cities',
        on_delete=models.CASCADE,
    )
    name = models.fields.CharField(max_length=100)

    def __str__(self):
        return self.name


class Address(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    city = models.ForeignKey(
        City,
        on_delete=models.CASCADE,
    )
    address = models.fields.CharField(max_length=300)
    user = models.ForeignKey(
        UserProfile,
        on_delete=models.CASCADE,
        null=True
    )

    def __str__(self):
        return '{} - {}'.format(self.address, self.city)



# TODO Refactor models


class Category(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=300)

    def __str__(self):
        return self.name


class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
    )
    name = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=300)

    amount = models.fields.PositiveIntegerField()
    stock = models.fields.PositiveIntegerField()

    active = models.fields.BooleanField(default=True)

    def __str__(self):
        return self.name


class Imagen(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
    )
    upload = models.FileField(upload_to='media/')
    name = models.fields.CharField(max_length=100)
    active = models.fields.BooleanField(default=True)




class Buy(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        UserProfile,
        on_delete=models.CASCADE,
    )
    address = models.ForeignKey(
        Address,
        on_delete=models.CASCADE,
    )

store/views.py
from django.shortcuts import render

# Create your views here.
from django.utils import timezone
from django.views.generic.detail import DetailView
from django.views.generic import ListView

from django.http import Http404
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

from rest_framework import viewsets
from rest_framework import permissions

from .serializers import ProductSerializer, CategorySerializer, CategoryListSerializer, ProductListSerializer, \
    CreateProductSerializer, CountryListSerializer, CountrySerializer,  CityListSerializer, CitySerializer
from .models import Product, Category, Country, City


class ProductDetailView(DetailView):
    model = Product
    template_name = 'product-detail.html'


class ProductListView(ListView):
    model = Product
    template_name = 'product-list.html'


class CategoryViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Category.objects.all()
    serializer_class = CategoryListSerializer
    permission_classes = [permissions.IsAuthenticated]


class ProductList(APIView):
    """
    List all snippets, or create a new snippet.
    """
    def get(self, request, format=None):
        product = Product.objects.all()
        serializer = ProductListSerializer(product, many=True)
        data = serializer.data
        return Response(data)

    def post(self, request, format=None):
        serializer = CreateProductSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)


class ProductDetail(APIView):
    """
    Retrieve, update or delete a snippet instance.
    """
    def get_object(self, pk):
        try:
            return Product.objects.get(pk=pk)
        except Product.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        product = self.get_object(pk)
        serializer = ProductSerializer(product)
        data = serializer.data

        data['ingreso proyectado'] = data['stock'] * data['amount']
        data['tax'] = data['amount'] * 0.19

        return Response(data)

    def put(self, request, pk, format=None):
        product = self.get_object(pk)
        serializer = ProductSerializer(product, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        product = self.get_object(pk)
        product.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class CategoryList(APIView):
    """
    List all snippets, or create a new snippet.
    """

    def get(self, request, format=None):
        category = Category.objects.all()
        serializer = CategoryListSerializer(category, many=True)
        data = serializer.data
        return Response(data)

    def post(self, request, format=None):
        serializer = CategoryListSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)


class CategoryDetail(APIView):
    """
    Retrieve, update or delete a snippet instance.
    """

    def get_object(self, pk):
        try:
            return Category.objects.get(pk=pk)
        except Category.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        category = self.get_object(pk)
        serializer = CategorySerializer(category)
        return Response(serializer.data)

    def put(self, request, pk, format=None):
        category = self.get_object(pk)
        serializer = CategorySerializer(category, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        category = self.get_object(pk)
        category.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class CountryList(APIView):
    """
    List all snippets, or create a new snippet.
    """
    def get(self, request, format=None):
        country = Country.objects.all()
        serializer = CountryListSerializer(country, many=True)
        data = serializer.data
        return Response(data)

    def post(self, request, format=None):
        serializer = CountryListSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)


class CountryDetail(APIView):
    """
    Retrieve, update or delete a snippet instance.
    """
    def get_object(self, pk):
        try:
            return Country.objects.get(pk=pk)
        except Country.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        country = self.get_object(pk)
        serializer = CountrySerializer(country)
        return Response(serializer.data)

    def put(self, request, pk, format=None):
        country = self.get_object(pk)
        serializer = CountrySerializer(country, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        country = self.get_object(pk)
        country.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)


class CityList(APIView):
    """
    List all snippets, or create a new snippet.
    """
    def get(self, request, format=None):
        city = City.objects.all()
        serializer = CityListSerializer(city, many=True)
        data = serializer.data
        return Response(data)

    def post(self, request, format=None):
        serializer = CityListSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)


class CityDetail(APIView):
    """
    Retrieve, update or delete a snippet instance.
    """
    def get_object(self, pk):
        try:
            return City.objects.get(pk=pk)
        except City.DoesNotExist:
            raise Http404

    def get(self, request, pk, format=None):
        city = self.get_object(pk)
        serializer = CitySerializer(city)
        return Response(serializer.data)

    def put(self, request, pk, format=None):
        city = self.get_object(pk)
        serializer = CitySerializer(city, data=request.data, partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        city = self.get_object(pk)
        city.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

store/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Mi titulo {% endblock %}</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block statics %}

    {% endblock %}

</head>
<body>
    {% include 'nav.html' %}

    {% block content %}
    mi content
    {% endblock %}
</body>
</html>

store/templates/login.html
{% extends 'base.html' %}

{% block statics %}
<style type="text/css">
    @font-face {
      font-weight: 400;
      font-style:  normal;
      font-family: 'Circular-Loom';
    
      src: url('https://cdn.loom.com/assets/fonts/circular/CircularXXWeb-Book-cd7d2bcec649b1243839a15d5eb8f0a3.woff2') format('woff2');
    }
    
    @font-face {
      font-weight: 500;
      font-style:  normal;
      font-family: 'Circular-Loom';
    
      src: url('https://cdn.loom.com/assets/fonts/circular/CircularXXWeb-Medium-d74eac43c78bd5852478998ce63dceb3.woff2') format('woff2');
    }
    
    @font-face {
      font-weight: 700;
      font-style:  normal;
      font-family: 'Circular-Loom';
    
      src: url('https://cdn.loom.com/assets/fonts/circular/CircularXXWeb-Bold-83b8ceaf77f49c7cffa44107561909e4.woff2') format('woff2');
    }
    
    @font-face {
      font-weight: 900;
      font-style:  normal;
      font-family: 'Circular-Loom';
    
      src: url('https://cdn.loom.com/assets/fonts/circular/CircularXXWeb-Black-bf067ecb8aa777ceb6df7d72226febca.woff2') format('woff2');
    }</style>
{% endblock %}

{% block content %}

<div class="container">

    <form class="form-signin">
      <h2 class="form-signin-heading">Please sign in</h2>
      <label for="inputEmail" class="sr-only">Email address</label>
      <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="">
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" id="inputPassword" class="form-control" placeholder="Password" required="">
      <div class="checkbox">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>

  </div>
    
         

{% endblock %}

store/templates/nav.html
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="{% url 'list' %}">MyEcommerce</a>
      </div>
      <!-- <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">Page 1</a></li>
        <li><a href="#">Page 2</a></li>
      </ul> -->
      <form class="navbar-form navbar-left" action="#">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Search" name="search">
          <div class="input-group-btn">
            <button class="btn btn-default" type="submit">
              <i class="glyphicon glyphicon-search"></i>
            </button>
          </div>
        </div>
      </form>

      <ul class="nav navbar-nav navbar-right">

        {% if user.is_authenticated %}
            <div class="dropdown">
                <button class="btn dropdown-toggle" type="button" data-toggle="dropdown">Profile
                <span class="caret"></span></button>
                <ul class="dropdown-menu">
                <li><a href="#">profile</a></li>
                <li><a href="#">carrito de compras</a></li>
                <li><a href="#">historico</a></li>
                <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-in"></span> Salir</a></li>
                </ul>
            </div>

        {% else %}

            <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-user"></span> Iniciar Session</a></li>
            <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-user"></span> Registrarse</a></li>

        {% endif %}



      </ul>



    </div>
  </nav>

store/templates/product-detail.html
{% extends 'base.html' %}

{% block statics %}

{% endblock %}

{% block content %}

<div class="container">

        {% if product.imagen_set.all %}
                <img src="{{ product.imagen_set.first.upload.url }}" alt="imagen">
{#            {{ product.imagen_set.all()[0].upload }}#}
        {% else %}
            <img class="card-img-top" src="https://www.w3schools.com/bootstrap4/img_avatar1.png" alt="Card image" >
        {% endif %}


          <h4 class="card-title">{{ product.name }}</h4>
          <p class="card-text"> {{ product.description }}</p>
          <a href="#" class="btn btn-primary">add card
          </a>





</div>



{% endblock %}

store/templates/product-list.html
{% extends 'base.html' %}

{% block statics %}

{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        {% for product in object_list %}
            {% if product.active and product.stock%}
                <div class="col-sm-6 col-md-2">
                  <div class="card producto">
                      {% if product.imagen_set.first %}
                          <img src="{{ product.imagen_set.first.upload.url  }}" alt="Card image" style="width:200px;height:200px;">
                      {% else %}
                          <img class="card-img-top" src="https://www.w3schools.com/bootstrap4/img_avatar1.png" alt="Card image" style="width:100%">
                      {% endif %}
                    <div class="card-body">
                      <h4 class="card-title">{{ product.name }}</h4>
                      <h3 class="card-title">{{ product.amount }}</h3>
                      <p class="card-text">{{ product.description }}</p>
                      <a href="{% url 'detail' pk=product.id  %}" class="btn btn-primary">ver producto</a>
                    </div>
                  </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
  </div>







</div>



{% endblock %}